// imports/ui/Clock.svelte
<script>
  import moment from 'moment'
  import { onMount } from 'svelte';
  import ClockSunriseSunset from './ClockSunriseSunset.svelte'

  let time = moment()

  onMount(async () => {
    let offset = moment().add(1, 'm').startOf('minute').diff(moment());

    setTimeout(function() {
      time = moment();

      setInterval(function ticker() {
        time = moment();
      }, 60 * 1000);
    }, offset);
  })

  $: timeString = time.format('H:mm')
</script>
 
 
<div class="container">
  <h1 class="display-1">
    { timeString }
  </h1>

  <ClockSunriseSunset/>
</div>

// client/ui/Clock.vue
<template lang="pug">
  .container
    .time-string.text-center {{ timeString }}
</template>

<script>
  import moment from 'moment';

  var timeString = function() {
    return moment().format('H:mm');
  };
  
  export default {
    data: function() {
      return {
        timeString: timeString()
      };
    },
    mounted: function() {
      let component = this;
      let offset = moment().add(1, 'm').startOf('minute').diff(moment());

      // NOTE: look into reliability of initial offset
      setTimeout(function() {
        component.timeString = timeString();

        setInterval(function ticker() {
          component.timeString = timeString();
        }, 60 * 1000);
      }, offset);
    },
  }
</script>

<style lang="scss" scoped>
  .container {
    position: relative;
  }
  .time-string {
    font-size: 6rem;
    position: relative;
    top: -40px;
  }
</style>
