// imports/ui/HomeScreen.svelte
<script>
  import Clock from './Clock.svelte'
  import ClockSunriseSunset from './ClockSunriseSunset.svelte'
</script>

<div class="container">
  <div class="row mt-5">
    <div class="col-4">
      <div class="d-flex justify-content-center">
        <div><Clock/></div>
      </div>

      <ClockSunriseSunset/>
    </div>
  </div>
</div>

// client/ui/HomeScreen.vue
<template lang="pug">
  .container
    .row
      .col-md-4
        clock
      .col-md-8
        weather
        
</template>

<script>
  import { Mongo } from 'meteor/mongo';

  export default {
    data: function() {
      return {
      };
    },
    meteor: {
      $subscribe: {
      },
    },
    methods: {
    }
  }
</script>
